baseURL = "http://example.org/"
languageCode = "en-us"
title = "Kiali"
theme = "canvas"

[menu]
  [[menu.mainleft]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1
  [[menu.mainleft]]
  identifier = "features"
  name = "Features"
  url = "/features"
  weight = 0
