baseURL = "http://example.org/"
languageCode = "en-us"
title = "Kiali"
theme = "canvas"

[menu]
  [[menu.mainleft]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1
  [[menu.mainright]]
  identifier = "swagger"
  name = "API"
  url = "/api"
  weight = 1
  [[menu.mainright]]
  identifier = "overview"
  name = "Overview"
  url = "/api/overview"
  weight = 1
  parent="swagger"
  [[menu.mainright]]
  identifier = "paths"
  name = "Paths"
  url = "/api/paths"
  weight = 2
  parent="swagger"
  [[menu.mainright]]
  identifier = "definitions"
  name = "Definitions"
  url = "/api/definitions"
  weight = 3
  parent="swagger"
